apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: apisec-lab
  region: us-east-1
  version: '1.24'
  tags:
    karpenter.sh/discovery: apisec-lab-karpenter

iam:
  withOIDC: true

karpenter:
  version: 'v0.19.5' # Exact version must be provided
  createServiceAccount: true # default is false

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    privateNetworking: true

addons:
- name: vpc-cni # no version is specified so it deploys the default version
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest

vpc:
  cidr: 10.30.0.0/16
  autoAllocateIPv6: true
# disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
