apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: HEAD
    helm:
      releaseName: portainer
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
